name: i_chef_application
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  curved_navigation_bar: ^1.0.6
  glass: ^2.0.0+2
  shared_preferences: ^2.5.3
  introduction_screen: ^3.1.17
  flutter_neat_and_clean_calendar: ^0.4.16
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  http: ^1.4.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/food.png
  uses-material-design: true
