// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpSymZzp3M8V3ZF_SgtcqMiHBeXZSb90',
    appId: '1:770599955242:web:d969dcd4fa258fcefa4c53',
    messagingSenderId: '770599955242',
    projectId: 'chef-intelligence-app',
    authDomain: 'chef-intelligence-app.firebaseapp.com',
    storageBucket: 'chef-intelligence-app.firebasestorage.app',
    measurementId: 'G-9NTGSR2XJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDl17Jww1rhoPwwanvj8gmqIl90dahiXM',
    appId: '1:770599955242:android:258bdcd3a431906dfa4c53',
    messagingSenderId: '770599955242',
    projectId: 'chef-intelligence-app',
    storageBucket: 'chef-intelligence-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA566EjcMe1Z_5Ts0IOze2d7D9WCbKMVVk',
    appId: '1:770599955242:ios:84563207dd6fc14afa4c53',
    messagingSenderId: '770599955242',
    projectId: 'chef-intelligence-app',
    storageBucket: 'chef-intelligence-app.firebasestorage.app',
    iosBundleId: 'com.example.iChefApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA566EjcMe1Z_5Ts0IOze2d7D9WCbKMVVk',
    appId: '1:770599955242:ios:84563207dd6fc14afa4c53',
    messagingSenderId: '770599955242',
    projectId: 'chef-intelligence-app',
    storageBucket: 'chef-intelligence-app.firebasestorage.app',
    iosBundleId: 'com.example.iChefApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDpSymZzp3M8V3ZF_SgtcqMiHBeXZSb90',
    appId: '1:770599955242:web:1dbeb354c877dbc3fa4c53',
    messagingSenderId: '770599955242',
    projectId: 'chef-intelligence-app',
    authDomain: 'chef-intelligence-app.firebaseapp.com',
    storageBucket: 'chef-intelligence-app.firebasestorage.app',
    measurementId: 'G-PC7J32R1WQ',
  );
}
